from quantization.mixed_modules.non_parametric.arbitrary_function import MQNonParametricFunction1D
from quantization.mixed_modules.non_parametric.activations import MQReLU, MQSigmoid
from quantization.mixed_modules.non_parametric.message_passing import MQMessagePassing
# from quantization.mixed_modules.non_parametric.max_pooling import QMaxPooling2D
from quantization.mixed_modules.non_parametric.input_quantizer import MQInput
